# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-30 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='bodytext',
            field=models.TextField(blank=True, verbose_name='Page Content'),
        ),
    ]
